### ISSUE TITLE
Site is in Spanish if browser prefers German (Accept-Language)

### ISSUE THREAD

**Issue by fnorf** [impronunciable/hackdash#156]
If you visit https://hackdash.org/ with a browser that prefers German (de) in its Accept-Language header the site will be shown in Spanish. It should fall back on English if German is not available ;)

You can check the language your browser prefers on https://ajaxhttpheaders2.appspot.com/?callback=wtf

**Comment by impronunciable** [comment]
@fnorf this is a bug, it should default to english. Thanks for pointing out!

**Comment by impronunciable** [comment]
@pjnovas where can we change this default?

**Comment by montogeek** [comment]
https://support.google.com/chromebook/answer/1059490?hl=en

**Comment by impronunciable** [comment]
@montogeek the issue is that if we don't support a language we should fallback to english, not spanish. Am I missing something from your link?

**Comment by montogeek** [comment]
Sorry, it thought about the browser config

**Comment by pjnovas** [comment]
@impronunciable hey!, that's weird the default is being get from [here](https://github.com/impronunciable/hackdash/blob/master/client/app/Initializer.js#L30-L33) it should be falling back to EN

**Comment by pjnovas** [comment]
@impronunciable oh I saw it!, it should be changed [HERE](https://github.com/impronunciable/hackdash/blob/master/client/app/locale/index.js#L7-L8), sorry!

**Comment by impronunciable** [comment]
Making the change

**Comment by impronunciable** [comment]
@pjnovas changed it @fnorf does it work for you now?

**Comment by fnorf** [comment]
Thanks for the quick fix!
