### ISSUE TITLE
Project Images not showing in dashboard embed

### ISSUE THREAD

**Issue by phillchill** [impronunciable/hackdash#158]
When I embed a dashboard via the 'share this dashboard' button, none of the project images show. Im on Chrome 53.0, OS X

Example: http://jsbin.com/natidu/1/edit?html,output

btw, already in the preview of the embed modal the images aren't displayed.

**Comment by phillchill** [comment]
same issue exists on embedding individual projects:
![screen shot 2016-10-13 at 11 11 25](https://cloud.githubusercontent.com/assets/902958/19343325/1473e51a-9136-11e6-81ef-7f152d06b029.png)

**Comment by impronunciable** [comment]
@phillchill good catch and easy fix.

**Comment by impronunciable** [comment]
It's working now for me. Let me know if the issue persist

**Comment by phillchill** [comment]
nice one! works for me 👍
